server:
  port: ${PORT:8080}

# Spring configuration
spring:
  application:
    name: "@project.name@"

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      client:
        observations:
          log-prompt: true
          log-completion: true
      memory:
        repository:
          jdbc:
            initialize-schema: always

  datasource:
    url: jdbc:h2:file:./store/data/hbca;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

# Vaadin configuration
vaadin:
  # Launch the default browser when starting the application in development mode
  launch-browser: true
  # To improve the performance during development.
  # For more information https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
  allowed-packages: "com.vaadin,org.vaadin,com.flowingcode,rs.siriusxi.hbca"

# Logging configuration
logging:
  level:
    org.atmosphere: warn
    rs.siriusxi.ai.hbca: info
    org.springframework.ai: debug
